/** ITC lexicon — short spoken hits for sweep locks. */
export const LEXICON = [
  "yes", "no", "maybe", "never", "always", "hello", "goodbye", "wait",
  "stop", "go", "stay", "leave", "come", "back", "here", "there",
  "near", "far", "behind", "ahead", "under", "over", "inside", "outside",
  "left", "right", "down", "up", "now", "later", "soon", "tonight",
  "help", "look", "listen", "see", "hear", "feel", "hide", "run",
  "don't", "can't", "won't", "prove", "speak", "ask", "answer", "silence",
  "quiet", "loud", "soft", "fast", "slow", "true", "false", "real",
  "fake", "open", "close", "push", "pull", "hold", "drop", "take",
  "give", "bring", "carry", "follow", "lead", "show", "find", "lose",
  "keep", "mother", "father", "child", "baby", "son", "daughter", "man",
  "woman", "boy", "girl", "friend", "stranger", "neighbor", "teacher", "priest",
  "nurse", "doctor", "soldier", "sailor", "farmer", "worker", "owner", "guest",
  "dead", "alive", "lost", "found", "alone", "together", "home", "house",
  "room", "door", "window", "stairs", "attic", "basement", "cellar", "kitchen",
  "hallway", "closet", "mirror", "photo", "bed", "chair", "table", "floor",
  "wall", "roof", "garden", "well", "woods", "field", "barn", "church",
  "school", "hospital", "graveyard", "cemetery", "bridge", "river", "lake", "road",
  "path", "tunnel", "cold", "dark", "light", "warm", "hot", "ice",
  "fire", "smoke", "water", "blood", "pain", "peace", "love", "hate",
  "fear", "hope", "anger", "sorry", "forgive", "forget", "remember", "dream",
  "sleep", "wake", "die", "live", "kill", "save", "hurt", "heal",
  "trap", "free", "watch", "name", "shadow", "voice", "spirit", "ghost",
  "demon", "angel", "portal", "energy", "entity", "presence", "haunt", "haunted",
  "curse", "bless", "prayer", "hymn", "cross", "bible", "rosary", "candle",
  "incense", "salt", "iron", "north", "south", "east", "west", "upstairs",
  "downstairs", "reflection", "corner", "ceiling", "crawlspace", "chimney", "fireplace", "boiler",
  "furnace", "pipe", "wire", "outlet", "breaker", "meter", "radio", "television",
  "telephone", "camera", "recorder", "battery", "flashlight", "laser", "grid", "rem",
  "emf", "gauss", "spike", "hit", "lock", "scan", "sweep", "band",
  "frequency", "static", "noise", "clip", "burst", "afraid", "brave", "calm",
  "confused", "curious", "desperate", "lonely", "mad", "sad", "tired", "hungry",
  "thirsty", "sick", "healthy", "trapped", "forgotten", "unfinished", "revenge", "justice",
  "mercy", "wrath", "jealousy", "envy", "pride", "shame", "guilt", "innocence",
  "head", "hand", "foot", "eye", "ear", "mouth", "heart", "bone",
  "skull", "neck", "chest", "arm", "leg", "finger", "throat", "lungs",
  "skin", "scar", "wound", "bruise", "fever", "cough", "about", "after",
  "again", "against", "almost", "along", "already", "also", "among", "another",
  "anyone", "anything", "around", "because", "before", "being", "below", "between",
  "beyond", "both", "broke", "built", "called", "came", "cannot", "caught",
  "cause", "change", "chief", "children", "city", "clear", "coming", "common",
  "could", "country", "course", "cover", "cried", "deal", "death", "deep",
  "did", "died", "does", "doing", "done", "during", "each", "early",
  "earth", "easy", "eat", "eight", "either", "else", "empty", "end",
  "enough", "even", "ever", "every", "everyone", "everything", "except", "face",
  "fact", "fall", "family", "feet", "few", "fight", "figure", "fill",
  "final", "fine", "finish", "first", "five", "fly", "food", "force",
  "four", "from", "front", "full", "further", "game", "gave", "get",
  "given", "goes", "going", "gone", "good", "got", "great", "green",
  "ground", "group", "grow", "had", "half", "happen", "hard", "has",
  "have", "having", "he", "heard", "heat", "held", "her", "high",
  "him", "himself", "his", "hour", "how", "however", "hundred", "idea",
  "if", "important", "into", "it", "its", "itself", "job", "join",
  "just", "kept", "kind", "knew", "know", "known", "land", "large",
  "last", "late", "laugh", "law", "lay", "learn", "less", "let",
  "letter", "life", "like", "line", "list", "little", "living", "long",
  "looked", "lot", "low", "made", "make", "making", "many", "march",
  "mark", "may", "mean", "meant", "meet", "men", "might", "mile",
  "mind", "mine", "miss", "more", "morning", "most", "move", "much",
  "must", "need", "new", "next", "night", "nine", "not", "nothing",
  "number", "off", "often", "oil", "old", "once", "one", "only",
  "onto", "or", "order", "other", "our", "out", "own", "page",
  "paper", "part", "pass", "past", "people", "perhaps", "person", "picture",
  "place", "plant", "play", "point", "poor", "possible", "power", "present",
  "press", "put", "question", "quick", "rain", "ran", "rather", "read",
  "ready", "red", "rest", "rock", "said", "same", "saw", "say",
  "says", "sea", "second", "seem", "seen", "self", "send", "sense",
  "sent", "set", "seven", "several", "shall", "she", "short", "should",
  "side", "simple", "since", "six", "small", "so", "some", "someone",
  "something", "sometimes", "sound", "special", "stand", "start", "state", "still",
  "stood", "story", "street", "strong", "study", "such", "sun", "sure",
  "taken", "talk", "tell", "ten", "than", "that", "the", "their",
  "them", "then", "these", "they", "thing", "think", "this", "those",
  "though", "thought", "three", "through", "time", "to", "today", "told",
  "too", "took", "toward", "town", "tree", "tried", "try", "turn",
  "turned", "two", "until", "upon", "us", "use", "used", "very",
  "walk", "want", "war", "was", "way", "we", "week", "went",
  "were", "what", "when", "where", "whether", "which", "while", "white",
  "who", "whole", "why", "wide", "wife", "will", "wind", "wish",
  "with", "within", "without", "women", "word", "work", "world", "would",
  "write", "year", "yet", "you", "young", "your", "behind you", "help me",
  "find me", "I'm here", "I'm cold", "I'm lost", "get out", "go away", "come here", "don't look",
  "look down", "look left", "look right", "still here", "too late", "not yet", "the door", "the stairs",
  "the attic", "the well", "my name", "right now", "over there", "leave now", "stay quiet", "it's me",
  "I died", "can't leave", "can't rest", "knock three", "thirteen", "hello hello", "is anyone there", "speak now",
  "prove it", "who are you", "what happened", "why here", "help me please", "I'm sorry", "forgive me", "I died here",
  "go upstairs", "go downstairs", "open the door", "close the door", "turn around", "don't turn", "watch out", "behind the wall",
  "under floor", "in the attic", "in the basement", "at the well", "by the tree", "three knocks", "two knocks", "one knock",
  "listen close", "record this", "ask again", "ask who", "ask when", "ask where", "ask why", "can you hear me",
  "are you alone", "are you dead", "did you die", "were you murdered", "was it an accident", "do you hurt", "are you trapped", "can you leave",
  "do you want help", "should we leave", "is it safe", "is it dangerous", "who killed you", "what is your name", "how old are you", "what year",
  "show yourself", "make a sound", "move something", "touch my hand", "use the box", "use the light", "use the meter", "speak through this",
  "I'm listening", "leave us alone", "clap once", "clap twice", "the baby", "the fire", "the key", "the photo",
  "the truth", "the priest", "my grave", "my house", "my child", "my mother", "my father", "my brother",
  "my sister", "the nurse", "the soldier", "the owner", "the stranger", "it's cold", "it's dark", "come closer",
  "speak louder", "say my name", "don't go", "stay here", "look away", "behind the door", "under the bed", "in the closet",
  "on the stairs", "at the window", "in the mirror", "in the photo", "in the woods", "by the river", "at the church", "in the hospital",
  "in the school", "in the barn", "1", "2", "3", "4", "5", "6",
  "7", "8", "9", "10", "11", "12", "13", "14",
  "15", "16", "17", "18", "19", "20", "21", "22",
  "23", "24", "25", "26", "27", "28", "29", "30",
  "40", "50", "60", "70", "80", "90", "100", "1000",
  "1800", "1805", "1810", "1815", "1820", "1825", "1830", "1835",
  "1840", "1845", "1850", "1855", "1860", "1865", "1870", "1875",
  "1880", "1885", "1890", "1895", "1900", "1905", "1910", "1915",
  "1920", "1925", "1930", "1935", "1940", "1945", "1950", "1955",
  "1960", "1965", "1970", "1975", "1980", "1985", "1990", "1995",
  "2000", "2005", "2010", "2015", "2020", "2025", "mary", "john",
  "james", "robert", "michael", "william", "david", "richard", "joseph", "thomas",
  "charles", "susan", "jennifer", "linda", "patricia", "elizabeth", "barbara", "margaret",
  "jessica", "sarah", "karen", "nancy", "betty", "helen", "sandra", "ashley",
  "emily", "amanda", "melissa", "deborah", "stephanie", "rebecca", "sharon", "laura",
  "cynthia", "angela", "michelle", "anna", "martha", "rachel", "victoria", "catherine",
  "josephine", "frances", "eleanor", "anne", "claire", "lucy", "rose", "grace",
  "henry", "george", "edward", "arthur", "frank", "harry", "albert", "samuel",
  "peter", "paul", "luke", "jack", "oliver", "noah", "leo", "signal 1",
  "echo 1", "hit 1", "burst 1", "pulse 1", "tone 1", "band 1", "lock 1", "sweep 1",
  "static 1", "signal 2", "echo 2", "hit 2", "burst 2", "pulse 2", "tone 2", "band 2",
  "lock 2", "sweep 2", "static 2", "signal 3", "echo 3", "hit 3", "burst 3", "pulse 3",
  "tone 3", "band 3", "lock 3", "sweep 3", "static 3", "signal 4", "echo 4", "hit 4",
  "burst 4", "pulse 4", "tone 4", "band 4", "lock 4", "sweep 4", "static 4", "signal 5",
  "echo 5", "hit 5", "burst 5", "pulse 5", "tone 5", "band 5", "lock 5", "sweep 5",
  "static 5", "signal 6", "echo 6", "hit 6", "burst 6", "pulse 6", "tone 6", "band 6",
  "lock 6", "sweep 6", "static 6", "signal 7", "echo 7", "hit 7", "burst 7", "pulse 7",
  "tone 7", "band 7", "lock 7", "sweep 7", "static 7", "signal 8", "echo 8", "hit 8",
  "burst 8", "pulse 8", "tone 8", "band 8", "lock 8", "sweep 8", "static 8", "signal 9",
  "echo 9", "hit 9", "burst 9", "pulse 9", "tone 9", "band 9", "lock 9", "sweep 9",
  "static 9", "signal 10", "echo 10", "hit 10", "burst 10", "pulse 10", "tone 10", "band 10",
  "lock 10", "sweep 10", "static 10", "signal 11", "echo 11", "hit 11", "burst 11", "pulse 11",
  "tone 11", "band 11", "lock 11", "sweep 11", "static 11", "signal 12", "echo 12", "hit 12",
  "burst 12", "pulse 12", "tone 12", "band 12", "lock 12", "sweep 12", "static 12", "signal 13",
  "echo 13", "hit 13", "burst 13", "pulse 13", "tone 13", "band 13", "lock 13", "sweep 13",
  "static 13", "signal 14", "echo 14", "hit 14", "burst 14", "pulse 14", "tone 14", "band 14",
  "lock 14", "sweep 14", "static 14", "signal 15", "echo 15", "hit 15", "burst 15", "pulse 15",
  "tone 15", "band 15", "lock 15", "sweep 15", "static 15", "signal 16", "echo 16", "hit 16",
  "burst 16", "pulse 16", "tone 16", "band 16", "lock 16", "sweep 16", "static 16", "signal 17",
  "echo 17", "hit 17", "burst 17", "pulse 17", "tone 17", "band 17", "lock 17", "sweep 17",
  "static 17", "signal 18", "echo 18", "hit 18", "burst 18", "pulse 18", "tone 18", "band 18",
  "lock 18", "sweep 18", "static 18", "signal 19", "echo 19", "hit 19", "burst 19", "pulse 19",
  "tone 19", "band 19", "lock 19", "sweep 19", "static 19", "signal 20", "echo 20", "hit 20",
  "burst 20", "pulse 20", "tone 20", "band 20", "lock 20", "sweep 20", "static 20", "signal 21",
  "echo 21", "hit 21", "burst 21", "pulse 21", "tone 21", "band 21", "lock 21", "sweep 21",
  "static 21", "signal 22", "echo 22", "hit 22", "burst 22", "pulse 22", "tone 22", "band 22",
  "lock 22", "sweep 22", "static 22", "signal 23", "echo 23", "hit 23", "burst 23", "pulse 23",
  "tone 23", "band 23", "lock 23", "sweep 23", "static 23", "signal 24", "echo 24", "hit 24",
  "burst 24", "pulse 24", "tone 24", "band 24", "lock 24", "sweep 24", "static 24", "signal 25",
  "echo 25", "hit 25", "burst 25", "pulse 25", "tone 25", "band 25", "lock 25", "sweep 25",
  "static 25", "signal 26", "echo 26", "hit 26", "burst 26", "pulse 26", "tone 26", "band 26",
  "lock 26", "sweep 26", "static 26", "signal 27", "echo 27", "hit 27", "burst 27", "pulse 27",
  "tone 27", "band 27", "lock 27", "sweep 27", "static 27", "signal 28", "echo 28", "hit 28",
  "burst 28", "pulse 28", "tone 28", "band 28", "lock 28", "sweep 28", "static 28", "signal 29",
  "echo 29", "hit 29", "burst 29", "pulse 29", "tone 29", "band 29", "lock 29", "sweep 29",
  "static 29", "signal 30", "echo 30", "hit 30", "burst 30", "pulse 30", "tone 30", "band 30",
  "lock 30", "sweep 30", "static 30", "signal 31", "echo 31", "hit 31", "burst 31", "pulse 31",
  "tone 31", "band 31", "lock 31", "sweep 31", "static 31", "signal 32", "echo 32", "hit 32",
  "burst 32", "pulse 32", "tone 32", "band 32", "lock 32", "sweep 32", "static 32", "signal 33",
  "echo 33", "hit 33", "burst 33", "pulse 33", "tone 33", "band 33", "lock 33", "sweep 33",
  "static 33", "signal 34", "echo 34", "hit 34", "burst 34", "pulse 34", "tone 34", "band 34",
  "lock 34", "sweep 34", "static 34", "signal 35", "echo 35", "hit 35", "burst 35", "pulse 35",
  "tone 35", "band 35", "lock 35", "sweep 35", "static 35", "signal 36", "echo 36", "hit 36",
  "burst 36", "pulse 36", "tone 36", "band 36", "lock 36", "sweep 36", "static 36", "signal 37",
  "echo 37", "hit 37", "burst 37", "pulse 37", "tone 37", "band 37", "lock 37", "sweep 37",
  "static 37", "signal 38", "echo 38", "hit 38", "burst 38", "pulse 38", "tone 38", "band 38",
  "lock 38", "sweep 38", "static 38", "signal 39", "echo 39", "hit 39", "burst 39", "pulse 39",
  "tone 39", "band 39", "lock 39", "sweep 39", "static 39", "signal 40", "echo 40", "hit 40",
  "burst 40", "pulse 40", "tone 40", "band 40", "lock 40", "sweep 40", "static 40", "signal 41",
  "echo 41", "hit 41", "burst 41", "pulse 41", "tone 41", "band 41", "lock 41", "sweep 41",
  "static 41", "signal 42", "echo 42", "hit 42", "burst 42", "pulse 42", "tone 42", "band 42",
  "lock 42", "sweep 42", "static 42", "signal 43", "echo 43", "hit 43", "burst 43", "pulse 43",
  "tone 43", "band 43", "lock 43", "sweep 43", "static 43", "signal 44", "echo 44", "hit 44",
  "burst 44", "pulse 44", "tone 44", "band 44", "lock 44", "sweep 44", "static 44", "signal 45",
  "echo 45", "hit 45", "burst 45", "pulse 45", "tone 45", "band 45", "lock 45", "sweep 45",
  "static 45", "signal 46", "echo 46", "hit 46", "burst 46", "pulse 46", "tone 46", "band 46",
  "lock 46", "sweep 46", "static 46", "signal 47", "echo 47", "hit 47", "burst 47", "pulse 47",
  "tone 47", "band 47", "lock 47", "sweep 47", "static 47", "signal 48", "echo 48", "hit 48",
  "burst 48", "pulse 48", "tone 48", "band 48", "lock 48", "sweep 48", "static 48", "signal 49",
  "echo 49", "hit 49", "burst 49", "pulse 49", "tone 49", "band 49", "lock 49", "sweep 49",
  "static 49", "signal 50", "echo 50", "hit 50", "burst 50", "pulse 50", "tone 50", "band 50",
  "lock 50", "sweep 50", "static 50", "signal 51", "echo 51", "hit 51", "burst 51", "pulse 51",
  "tone 51", "band 51", "lock 51", "sweep 51", "static 51", "signal 52", "echo 52", "hit 52",
  "burst 52", "pulse 52", "tone 52", "band 52", "lock 52", "sweep 52", "static 52", "signal 53",
  "echo 53", "hit 53", "burst 53", "pulse 53", "tone 53", "band 53", "lock 53", "sweep 53",
  "static 53", "signal 54", "echo 54", "hit 54", "burst 54", "pulse 54", "tone 54", "band 54",
  "lock 54", "sweep 54", "static 54", "signal 55", "echo 55", "hit 55", "burst 55", "pulse 55",
  "tone 55", "band 55", "lock 55", "sweep 55", "static 55", "signal 56", "echo 56", "hit 56",
  "burst 56", "pulse 56", "tone 56", "band 56", "lock 56", "sweep 56", "static 56", "signal 57",
  "echo 57", "hit 57", "burst 57", "pulse 57", "tone 57", "band 57", "lock 57", "sweep 57",
  "static 57", "signal 58", "echo 58", "hit 58", "burst 58", "pulse 58", "tone 58", "band 58",
  "lock 58", "sweep 58", "static 58", "signal 59", "echo 59", "hit 59", "burst 59", "pulse 59",
  "tone 59", "band 59", "lock 59", "sweep 59", "static 59", "signal 60", "echo 60", "hit 60",
  "burst 60", "pulse 60", "tone 60", "band 60", "lock 60", "sweep 60", "static 60", "signal 61",
  "echo 61", "hit 61", "burst 61", "pulse 61", "tone 61", "band 61", "lock 61", "sweep 61",
  "static 61", "signal 62", "echo 62", "hit 62", "burst 62", "pulse 62", "tone 62", "band 62",
  "lock 62", "sweep 62", "static 62", "signal 63", "echo 63", "hit 63", "burst 63", "pulse 63",
  "tone 63", "band 63", "lock 63", "sweep 63", "static 63", "signal 64", "echo 64", "hit 64",
  "burst 64", "pulse 64", "tone 64", "band 64", "lock 64", "sweep 64", "static 64", "signal 65",
  "echo 65", "hit 65", "burst 65", "pulse 65", "tone 65", "band 65", "lock 65", "sweep 65",
  "static 65", "signal 66", "echo 66", "hit 66", "burst 66", "pulse 66", "tone 66", "band 66",
  "lock 66", "sweep 66", "static 66", "signal 67", "echo 67", "hit 67", "burst 67", "pulse 67",
  "tone 67", "band 67", "lock 67", "sweep 67", "static 67", "signal 68", "echo 68", "hit 68",
  "burst 68", "pulse 68", "tone 68", "band 68", "lock 68", "sweep 68", "static 68", "signal 69",
  "echo 69", "hit 69", "burst 69", "pulse 69", "tone 69", "band 69", "lock 69", "sweep 69",
  "static 69", "signal 70", "echo 70", "hit 70", "burst 70", "pulse 70", "tone 70", "band 70",
  "lock 70", "sweep 70", "static 70", "signal 71", "echo 71", "hit 71", "burst 71", "pulse 71",
  "tone 71", "band 71", "lock 71", "sweep 71", "static 71", "signal 72", "echo 72", "hit 72",
  "burst 72", "pulse 72", "tone 72", "band 72", "lock 72", "sweep 72", "static 72", "signal 73",
  "echo 73", "hit 73", "burst 73", "pulse 73", "tone 73", "band 73", "lock 73", "sweep 73",
  "static 73", "signal 74", "echo 74", "hit 74", "burst 74", "pulse 74", "tone 74", "band 74",
  "lock 74", "sweep 74", "static 74", "signal 75", "echo 75", "hit 75", "burst 75", "pulse 75",
  "tone 75", "band 75", "lock 75", "sweep 75", "static 75", "signal 76", "echo 76", "hit 76",
  "burst 76", "pulse 76", "tone 76", "band 76", "lock 76", "sweep 76", "static 76", "signal 77",
  "echo 77", "hit 77", "burst 77", "pulse 77", "tone 77", "band 77", "lock 77", "sweep 77",
  "static 77", "signal 78", "echo 78", "hit 78", "burst 78", "pulse 78", "tone 78", "band 78",
  "lock 78", "sweep 78", "static 78", "signal 79", "echo 79", "hit 79", "burst 79", "pulse 79",
  "tone 79", "band 79", "lock 79", "sweep 79", "static 79", "signal 80", "echo 80", "hit 80",
  "burst 80", "pulse 80", "tone 80", "band 80", "lock 80", "sweep 80", "static 80", "signal 81",
  "echo 81", "hit 81", "burst 81", "pulse 81", "tone 81", "band 81", "lock 81", "sweep 81",
  "static 81", "signal 82", "echo 82", "hit 82", "burst 82", "pulse 82", "tone 82", "band 82",
  "lock 82", "sweep 82", "static 82", "signal 83", "echo 83", "hit 83", "burst 83", "pulse 83",
  "tone 83", "band 83", "lock 83", "sweep 83", "static 83", "signal 84", "echo 84", "hit 84",
  "burst 84", "pulse 84", "tone 84", "band 84", "lock 84", "sweep 84", "static 84", "signal 85",
  "echo 85", "hit 85", "burst 85", "pulse 85", "tone 85", "band 85", "lock 85", "sweep 85",
  "static 85", "signal 86", "echo 86", "hit 86", "burst 86", "pulse 86", "tone 86", "band 86",
  "lock 86", "sweep 86", "static 86", "signal 87", "echo 87", "hit 87", "burst 87", "pulse 87",
  "tone 87", "band 87", "lock 87", "sweep 87", "static 87", "signal 88", "echo 88", "hit 88",
  "burst 88", "pulse 88", "tone 88", "band 88", "lock 88", "sweep 88", "static 88", "signal 89",
  "echo 89", "hit 89", "burst 89", "pulse 89", "tone 89", "band 89", "lock 89", "sweep 89",
  "static 89", "signal 90", "echo 90", "hit 90", "burst 90", "pulse 90", "tone 90", "band 90",
  "lock 90", "sweep 90", "static 90", "signal 91", "echo 91", "hit 91", "burst 91", "pulse 91",
  "tone 91", "band 91", "lock 91", "sweep 91", "static 91", "signal 92", "echo 92", "hit 92",
  "burst 92", "pulse 92", "tone 92", "band 92", "lock 92", "sweep 92", "static 92", "signal 93",
  "echo 93", "hit 93", "burst 93", "pulse 93", "tone 93", "band 93", "lock 93", "sweep 93",
  "static 93", "signal 94", "echo 94", "hit 94", "burst 94", "pulse 94", "tone 94", "band 94",
  "lock 94", "sweep 94", "static 94", "signal 95", "echo 95", "hit 95", "burst 95", "pulse 95",
  "tone 95", "band 95", "lock 95", "sweep 95", "static 95", "signal 96", "echo 96", "hit 96",
  "burst 96", "pulse 96", "tone 96", "band 96", "lock 96", "sweep 96", "static 96", "signal 97",
  "echo 97", "hit 97", "burst 97", "pulse 97", "tone 97", "band 97", "lock 97", "sweep 97",
  "static 97", "signal 98", "echo 98", "hit 98", "burst 98", "pulse 98", "tone 98", "band 98",
  "lock 98", "sweep 98", "static 98", "signal 99",
] as const;

export type Word = (typeof LEXICON)[number] | string;

let wordSalt = 0;

export function pickWord(seed: number): string {
  // Advance salt so sticky audio hashes do not hammer the same handful of words.
  wordSalt = (wordSalt + 0x9e3779b9) >>> 0;
  const mixed = (Math.floor(Math.abs(seed) * 9973) ^ wordSalt ^ (wordSalt >>> 16)) >>> 0;
  return LEXICON[mixed % LEXICON.length]!;
}

export function lexiconSize(): number {
  return LEXICON.length;
}

export function hashBins(bins: Uint8Array, freq: number): number {
  let h = (freq * 1000) | 0;
  const step = Math.max(1, Math.floor(bins.length / 24));
  for (let i = 0; i < bins.length; i += step) {
    h = (h * 33 + bins[i]!) | 0;
  }
  h = Math.imul(h ^ (Date.now() & 0xffff), 232555121) >>> 0;
  return h >>> 0;
}

export function hashString(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 16777619);
  return h >>> 0;
}

const YESNO = [
  "yes",
  "no",
  "maybe",
  "never",
  "not yet",
  "sometimes",
  "I cannot",
  "goodbye",
  "yes yes",
  "no no",
  "not that",
  "ask again",
  "not now",
  "soon",
  "always",
  "cannot say",
  "don't know",
  "prove it",
  "listen",
  "wait",
  "absolutely",
  "negative",
  "uncertain",
  "unknown",
  "silence",
  "perhaps",
  "unlikely",
  "affirmative",
  "denied",
  "blocked",
  "unclear",
  "ask later",
  "strong yes",
  "strong no",
  "fifty fifty",
  "depends",
  "not sure",
  "impossible",
  "inevitable",
  "already decided",
];
const WHO = [
  "mother",
  "father",
  "child",
  "me",
  "him",
  "her",
  "the woman",
  "the man",
  "a child",
  "a soldier",
  "the owner",
  "nobody",
  "someone",
  "it's me",
  "mary",
  "john",
  "elizabeth",
  "robert",
  "the priest",
  "the nurse",
  "a girl",
  "a boy",
  "an old man",
  "an old woman",
  "the twin",
  "the neighbor",
  "the builder",
  "the miner",
  "the farmer",
  "the widow",
  "the orphan",
  "the thief",
  "the hunter",
  "the midwife",
  "the blacksmith",
  "the caretaker",
  "nobody you know",
  "someone upstairs",
  "someone downstairs",
  "the one in the photo",
  "the one behind you",
  "margaret",
  "william",
  "henry",
  "catherine",
  "samuel",
  "eleanor",
  "george",
];
const WHERE = [
  "here",
  "behind you",
  "attic",
  "basement",
  "the door",
  "the stairs",
  "outside",
  "under floor",
  "in the wall",
  "this house",
  "the well",
  "near you",
  "over there",
  "downstairs",
  "the woods",
  "my grave",
  "the hallway",
  "the closet",
  "the crawlspace",
  "the chimney",
  "the garden",
  "the barn",
  "the churchyard",
  "the bridge",
  "the cellar stairs",
  "behind the mirror",
  "under the bed",
  "inside the wall",
  "in the photograph",
  "near the window",
  "at the threshold",
  "the nursery",
  "the boiler room",
  "the orchard",
  "the riverbank",
  "my resting place",
];
const WHEN = [
  "now",
  "tonight",
  "never",
  "soon",
  "that night",
  "midnight",
  "always",
  "nineteen forty",
  "last winter",
  "not yet",
  "three am",
  "too late",
  "at dawn",
  "at dusk",
  "before sunrise",
  "after midnight",
  "years ago",
  "this hour",
  "on the anniversary",
  "during the storm",
  "in winter",
  "in summer",
  "eighteen ninety",
  "nineteen twelve",
  "nineteen twenty",
  "nineteen sixty",
  "two thousand",
  "long ago",
  "just now",
  "a moment ago",
  "every night",
  "when you leave",
];
const WHAT = [
  "help",
  "listen",
  "look",
  "the key",
  "the photo",
  "a secret",
  "the fire",
  "danger",
  "peace",
  "the baby",
  "the name",
  "wait",
  "the truth",
  "a warning",
  "a promise",
  "a debt",
  "a letter",
  "a ring",
  "a locket",
  "a map",
  "the stairs creaking",
  "the cold spot",
  "the footprint",
  "the whisper",
  "the knock",
  "the shadow",
  "the perfume",
  "the song",
  "the prayer",
  "the truth you avoid",
  "remember me",
  "protect them",
  "open the window",
  "close the circle",
];
const WHY = [
  "pain",
  "unfinished",
  "sorry",
  "trapped",
  "love",
  "anger",
  "forgotten",
  "can't leave",
  "can't rest",
  "I died",
  "the fire",
  "they know",
  "betrayal",
  "accident",
  "jealousy",
  "hunger",
  "illness",
  "drowning",
  "fall",
  "to warn you",
  "to protect",
  "to confess",
  "to finish",
  "to be heard",
  "to go home",
  "because of him",
  "because of her",
  "because of the fire",
  "they lied",
  "I was alone",
];
const HOW = [
  "listen",
  "follow",
  "stay",
  "leave now",
  "light a candle",
  "say my name",
  "look down",
  "don't look",
  "ask again",
  "record",
  "pray",
  "through the box",
  "through the light",
  "through the cold",
  "in dreams",
  "by knocking",
  "by shadow",
  "by smell",
  "by name",
  "stand still",
  "turn the light off",
  "open the recorder",
  "say the prayer",
  "leave an offering",
  "do not mock",
  "be respectful",
  "listen longer",
];
const OPEN = [
  "help me",
  "I'm here",
  "behind you",
  "leave now",
  "listen",
  "it's me",
  "not yet",
  "goodbye",
  "stay",
  "look left",
  "I'm cold",
  "find me",
  "the door",
  "yes",
  "no",
  "wait",
  "still here",
  "don't go",
  "come closer",
  "speak louder",
  "say my name",
  "leave us alone",
  "clap once",
  "clap twice",
  "it's cold",
  "it's dark",
  "I'm listening",
  "behind the door",
  "under the bed",
  "in the closet",
  "on the stairs",
  "at the window",
  "in the mirror",
  "show yourself",
  "make a sound",
  "move something",
  "touch my hand",
  "use the box",
  "use the light",
  "use the meter",
  "speak through this",
  "are you alone",
  "are you dead",
];

function bankFor(q: string): readonly string[] {
  const s = q.toLowerCase();
  if (/\bwho\b/.test(s)) return WHO;
  if (/\bwhere\b/.test(s)) return WHERE;
  if (/\bwhen\b/.test(s)) return WHEN;
  if (/\bwhy\b/.test(s)) return WHY;
  if (/\bhow\b/.test(s)) return HOW;
  if (/\bwhat\b/.test(s)) return WHAT;
  if (
    /^(are|is|am|was|were|do|does|did|can|will|would|should|have|has|could)\b/.test(s) ||
    /\b(anyone|there|alive|dead|with us|listening)\b/.test(s)
  ) {
    return YESNO;
  }
  return OPEN;
}

/** Spook Board short answer for a spoken/typed question. */
export function pickAnswer(question: string, salt: number): string {
  const bank = bankFor(question);
  const i = Math.abs((hashString(question.toLowerCase().trim()) ^ (salt | 0)) >>> 0) % bank.length;
  return bank[i] ?? "yes";
}
